name: Build & Test

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      QC_ALPACA_API_KEY: ${{ secrets.QC_ALPACA_API_KEY }}
      QC_ALPACA_API_SECRET: ${{ secrets.QC_ALPACA_API_SECRET }}
      QC_ALPACA_ACCESS_TOKEN: ${{ secrets.QC_ALPACA_ACCESS_TOKEN }}
      QC_ALPACA_PAPER_TRADING: ${{ secrets.QC_ALPACA_PAPER_TRADING }}
      QC_JOB_USER_ID: ${{ secrets.QC_JOB_USER_ID }}
      QC_API_ACCESS_TOKEN: ${{ secrets.QC_API_ACCESS_TOKEN }}
      QC_JOB_ORGANIZATION_ID: ${{ secrets.QC_JOB_ORGANIZATION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free space
        run: df -h && sudo rm -rf /usr/local/lib/android && sudo rm -rf /opt/ghc && rm -rf /opt/hostedtoolcache* && df -h

      - uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
          options: --workdir /__w/Lean.Brokerages.Alpaca/Lean.Brokerages.Alpaca -v /home/runner/work:/__w -e QC_ALPACA_API_KEY=${{ secrets.QC_ALPACA_API_KEY }} -e QC_ALPACA_API_SECRET=${{ secrets.QC_ALPACA_API_SECRET }} -e QC_ALPACA_ACCESS_TOKEN=${{ secrets.QC_ALPACA_ACCESS_TOKEN }} -e QC_ALPACA_PAPER_TRADING=${{ secrets.QC_ALPACA_PAPER_TRADING }} -e QC_JOB_USER_ID=${{ secrets.QC_JOB_USER_ID }} -e QC_API_ACCESS_TOKEN=${{ secrets.QC_API_ACCESS_TOKEN }} -e QC_JOB_ORGANIZATION_ID=${{ secrets.QC_JOB_ORGANIZATION_ID }}

      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - name: Build
        run: dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.AlpacaBrokerage.sln

      - name: Run Tests
        run: dotnet test ./QuantConnect.AlpacaBrokerage.Tests/bin/Release/QuantConnect.Brokerages.Alpaca.Tests.dll
